"""Text-to-SQL analytics agent: Ask / Schema explorer / Evaluation / Monitoring.

Run:  .venv\\Scripts\\streamlit run streamlit_app.py
"""
from __future__ import annotations

import datetime
import json
import sys
from pathlib import Path

import pandas as pd
import streamlit as st

ROOT = Path(__file__).resolve().parent
sys.path.insert(0, str(ROOT))

from src.config import load_config, path, questions_for  # noqa: E402

st.set_page_config(page_title="Text-to-SQL agent", page_icon=":mag:", layout="wide", initial_sidebar_state="expanded")

CFG = load_config()
RES = path("results")
ATTRIBUTION = (
    "Data: copies of the owner's four data science warehouses. Flight: US BTS on-time data (US government, public domain) and "
    "OurAirports airports (public domain); "
    "Fraud and Sales: synthetic data generated by the projects; Retail: UCI Online Retail II "
    "(Chen, 2019), CC BY 4.0. Golden questions and gold SQL were written by the builder.")
EXAMPLES = [
    "Which 5 origin airports have the most total weather delay minutes?",
    "What is the fraud rate for each channel?",
    "How many retail customers are in each RFM customer segment?",
    "Show total revenue per month in 2025 across all product categories.",
    "Which airlines had an on-time rate above 80%?",
    "What was the average ticket price on Delta flights?",
]
SERIES = ["#2f6fb0", "#e07b39", "#3a9d5d", "#b04a8f"]


# ---------------------------------------------------------------------------------------------
# cached resources and data
# ---------------------------------------------------------------------------------------------
@st.cache_resource(show_spinner="Loading schema catalogue and warehouse ...")
def shared():
    from src.executor import Executor
    from src.retrieval import SchemaRetriever

    a = CFG["agent"]
    return SchemaRetriever(), Executor(path("warehouse"), timeout_s=a["timeout_s"], max_rows=a["max_rows"])


def get_agent(config_name: str, model: str):
    from src.agent import Agent

    key = f"agent::{config_name}::{model}"
    if key not in st.session_state:
        retr, ex = shared()
        st.session_state[key] = Agent(config_name, model=model, trace_source="app", retriever=retr, executor=ex)
    return st.session_state[key]


@st.cache_data
def load_catalog():
    return json.loads(path("catalog").read_text(encoding="utf-8"))


def read_csv(name: str) -> pd.DataFrame | None:
    p = RES / name
    return pd.read_csv(p) if p.exists() else None


def read_jsonl(p: Path) -> list[dict]:
    if not p.exists():
        return []
    return [json.loads(x) for x in p.read_text(encoding="utf-8").splitlines() if x.strip()]


def draw_chart(df: pd.DataFrame, spec: dict) -> None:
    import altair as alt

    if spec.get("type") not in ("bar", "line") or df.empty:
        return
    x, ys = spec["x"], [y for y in spec["y"] if y in df.columns]
    if x not in df.columns or not ys:
        return
    d = df[[x] + ys].copy()
    long = d.melt(id_vars=[x], value_vars=ys, var_name="series", value_name="value")
    color = (alt.Color("series:N", scale=alt.Scale(range=SERIES), legend=alt.Legend(orient="top", title=None))
             if len(ys) > 1 else alt.value(SERIES[0]))
    if spec["type"] == "bar":
        ch = (alt.Chart(long).mark_bar(cornerRadiusEnd=2)
              .encode(y=alt.Y(f"{x}:N", sort="-x", title=None, axis=alt.Axis(labelLimit=260)),
                      x=alt.X("value:Q", title=ys[0], axis=alt.Axis(grid=True, gridOpacity=0.15)),
                      color=color, tooltip=[x, "value"])
              .properties(height=alt.Step(22)))
    else:
        xt = "T" if pd.api.types.is_datetime64_any_dtype(d[x]) or d[x].dtype == object else "O"
        if xt == "T":
            long[x] = pd.to_datetime(long[x])
        ch = (alt.Chart(long).mark_line(point=len(d) <= 40)
              .encode(x=alt.X(f"{x}:{xt}", title=x), y=alt.Y("value:Q", title=None,
                                                              axis=alt.Axis(grid=True, gridOpacity=0.15)),
                      color=color, tooltip=[x, "series", "value"])
              .properties(height=320))
    st.altair_chart(ch.configure_view(strokeWidth=0), width="stretch")


# ---------------------------------------------------------------------------------------------
# Ask
# ---------------------------------------------------------------------------------------------
def page_ask():
    st.title("Ask the data warehouse")
    st.caption("Plain-English questions about the flight, fraud, retail and sales warehouses. The agent "
               "retrieves the relevant tables, writes DuckDB SQL with a local model, runs it read-only and "
               "fixes its own errors.")
    with st.sidebar:
        st.subheader("Settings")
        models = CFG["llm"]["models_evaluated"]
        model = st.selectbox("Model (Ollama)", models, index=models.index(CFG["llm"]["model"]))
        configs = [c for c in CFG["ablations"] if c != "oracle_tables_upper"]
        config_name = st.selectbox("Agent configuration", configs, index=configs.index("full_agent"),
                                   help="full_agent = schema retrieval + docs + up to 3 self-corrections.")
    cols = st.columns(3)
    for i, ex in enumerate(EXAMPLES):
        if cols[i % 3].button(ex, key=f"ex{i}", width="stretch"):
            st.session_state["q"] = ex
    q = st.text_input("Question", key="q", placeholder="e.g. Which carrier had the most cancelled flights?")
    go = st.button("Ask", type="primary")
    if go and q.strip():
        from src.llm import OllamaUnavailable

        try:
            with st.spinner(f"Thinking with {model} (on a CPU this can take a few minutes) ..."):
                r = get_agent(config_name, model).ask(q.strip())
            st.session_state["last"] = r
        except OllamaUnavailable as e:
            st.error(str(e))
            return
    r = st.session_state.get("last")
    if r is None:
        st.info("Pick an example or type a question, then press **Ask**. Answers need Ollama running locally "
                f"with `{CFG['llm']['model']}` pulled.")
        return
    st.markdown(f"**Question:** {r.question}")
    if r.status == "refused":
        st.warning(f"Refused: {r.refusal_reason}")
    elif r.status != "ok":
        st.error(f"No answer after {len(r.attempts)} attempt(s): {r.error}")
    else:
        st.success(r.summary)
        df = pd.DataFrame(r.rows, columns=r.columns)
        draw_chart(df, r.chart)
        st.dataframe(df, width="stretch", hide_index=True, height=min(400, 38 + 35 * len(df)))
        if r.truncated:
            st.caption(f"Showing the first {len(df)} rows (maximum result size).")
    if r.sql:
        with st.expander("Generated SQL", expanded=r.status != "ok"):
            st.code(r.sql, language="sql")
    with st.expander(f"Attempts log ({len(r.attempts)})"):
        for a in r.attempts:
            outcome = (f"guardrail block: {a['guard_reason']}" if a["guard_reason"] else
                       f"error: {a['error']}" if a["error"] else
                       f"{a['n_rows']} rows" if a["n_rows"] is not None else "refusal / no SQL")
            st.markdown(f"**Attempt {a['n']}**: {outcome} - LLM {a['t_llm']:.1f}s, "
                        f"{a['prompt_tokens']} prompt + {a['completion_tokens']} completion tokens")
            if a["sql"]:
                st.code(a["sql"], language="sql")
    st.caption(f"Tables given to the model: {', '.join(t for t, _ in r.retrieved[:10])}"
               f"{' ...' if len(r.retrieved) > 10 else ''} | total {r.t_total:.1f}s "
               f"(LLM {r.t_llm:.1f}s, SQL {r.t_exec * 1000:.0f} ms) | model {r.model} | config {r.config}")


# ---------------------------------------------------------------------------------------------
# Schema explorer
# ---------------------------------------------------------------------------------------------
def page_schema():
    st.title("Schema explorer")
    cat = load_catalog()
    schemas = sorted({t["schema"] for t in cat})
    man = pd.read_csv(path("manifest"))
    k = st.columns(4)
    k[0].metric("Schemas", len(schemas))
    k[1].metric("Tables", len(cat))
    k[2].metric("Columns", sum(len(t["columns"]) for t in cat))
    k[3].metric("Rows", f"{int(man['rows'].sum()):,}")
    s = st.radio("Project schema", schemas, horizontal=True)
    tabs = [t for t in cat if t["schema"] == s]
    if tabs and tabs[0].get("project"):
        st.caption(tabs[0]["project"])
    st.dataframe(pd.DataFrame([{"table": t["fq"], "rows": t["rows"], "columns": len(t["columns"]),
                                "description": t["description"]} for t in tabs]),
                 width="stretch", hide_index=True,
                 column_config={"rows": st.column_config.NumberColumn(format="localized")})
    for t in tabs:
        with st.expander(f"{t['fq']}  ({t['rows']:,} rows)"):
            st.markdown(t["description"] or "_No description in dbt._")
            st.dataframe(pd.DataFrame([{"column": c["name"], "type": c["type"], "description": c["description"],
                                        "examples": ", ".join(map(str, c["samples"]))} for c in t["columns"]]),
                         width="stretch", hide_index=True)
    st.caption("Descriptions come from each project's dbt schema.yml plus builder-written notes "
               "(data/column_notes.yaml); types and examples from the DuckDB copy. " + ATTRIBUTION)


# ---------------------------------------------------------------------------------------------
# Evaluation
# ---------------------------------------------------------------------------------------------
def page_eval():
    st.title("Evaluation")
    st.caption("Execution accuracy on a builder-written golden set: 90 questions with verified gold SQL "
               "(15 per difficulty level) + 10 unanswerable questions. Split: dev 30 / test 70, stratified, seed 42.")
    summ = read_csv("summary_test.csv")
    if summ is None:
        st.info("**Test-set evaluation: not run yet.** The batch evaluations run on the GPU machine "
                "(`scripts\\run_queue_task.cmd`). This page fills in automatically once "
                "`results/summary_test.csv` exists.")
    else:
        if not summ["complete"].all():
            st.warning("Some runs are incomplete (n_done < n_split); numbers below are partial.")
        show = summ.copy()
        st.subheader("Ablations (test)")
        st.dataframe(show, width="stretch", hide_index=True)
        import altair as alt

        long = show.melt(id_vars=["config"], value_vars=["exec_acc_answerable", "refusal_acc_unanswerable"],
                         var_name="metric", value_name="value").dropna()
        ch = (alt.Chart(long).mark_bar()
              .encode(y=alt.Y("config:N", title=None, sort=list(show["config"])),
                      x=alt.X("value:Q", scale=alt.Scale(domain=[0, 1]), title=None),
                      color=alt.Color("metric:N", scale=alt.Scale(range=SERIES[:2]),
                                      legend=alt.Legend(orient="top", title=None)),
                      yOffset="metric:N", tooltip=["config", "metric", alt.Tooltip("value:Q", format=".3f")])
              .properties(height=alt.Step(16)))
        st.altair_chart(ch.configure_view(strokeWidth=0), width="stretch")
        bd = read_csv("by_difficulty_test.csv")
        if bd is not None:
            st.subheader("Accuracy by difficulty")
            st.dataframe(bd.pivot(index="difficulty", columns="config", values="accuracy"), width="stretch")
        ea = RES / "error_analysis_test.json"
        if ea.exists():
            st.subheader("Error analysis (rule-based buckets)")
            data = json.loads(ea.read_text(encoding="utf-8"))
            cfg_sel = st.radio("Run", list(data), horizontal=True, key="ea_cfg")
            b = data[cfg_sel]["buckets"]
            st.dataframe(pd.DataFrame([{"bucket": k, "count": v["count"]} for k, v in b.items()]),
                         hide_index=True)
            for k, v in b.items():
                with st.expander(f"{k} ({v['count']})"):
                    for e in v["examples"]:
                        st.markdown(f"**{e['id']}** {e['question']}  \n_{e['reason']}_")
                        st.code(f"-- gold\n{e['gold_sql']}\n-- predicted\n{e['pred_sql']}", language="sql")
        st.subheader("Per-question browser")
        runs = sorted((RES / "scored").glob("test__*.jsonl"))
        if runs:
            run = st.selectbox("Run", [p.stem.split("__", 1)[1] for p in runs])
            rows = read_jsonl(RES / "scored" / f"test__{run}.jsonl")
            df = pd.DataFrame(rows)
            filt = st.radio("Show", ["all", "correct", "wrong"], horizontal=True)
            if filt != "all":
                df = df[df["correct"] == (filt == "correct")]
            st.dataframe(df[["id", "difficulty", "correct", "status", "n_attempts", "t_total", "reason", "question"]],
                         width="stretch", hide_index=True)
            pick = st.selectbox("Question", list(df["id"]))
            if pick:
                r = df[df["id"] == pick].iloc[0]
                st.code(f"-- gold\n{r['gold_sql']}\n-- predicted\n{r['pred_sql']}", language="sql")

    st.subheader("Already available (no LLM needed)")
    c1, c2 = st.columns(2)
    with c1:
        st.markdown("**Schema retrieval on dev** (table recall of gold-SQL tables vs. tables given to the model)")
        rd = read_csv("retrieval_dev.csv")
        if rd is not None:
            st.dataframe(rd, hide_index=True, width="stretch")
            st.caption(f"Chosen on dev: top {CFG['retrieval']['top_tables']} tables.")
    with c2:
        smoke = RES / "smoke_test.json"
        st.markdown("**Smoke test** (a few dev questions end to end; not an evaluation)")
        if smoke.exists():
            sm = pd.DataFrame(json.loads(smoke.read_text(encoding="utf-8")))
            st.dataframe(sm[["id", "model", "status", "correct", "n_attempts", "t_total"]], hide_index=True,
                         width="stretch")
        else:
            st.write("not run yet")
    with st.expander("Golden set (all 100 questions with gold SQL)"):
        g = pd.DataFrame(questions_for("all"))
        splits = json.loads(path("splits").read_text(encoding="utf-8"))
        g["split"] = g["id"].map(lambda i: "dev" if i in set(splits["dev"]) else "test")
        st.dataframe(g[["id", "split", "difficulty", "question", "gold_sql", "gold_rows", "order_matters"]],
                     width="stretch", hide_index=True)


# ---------------------------------------------------------------------------------------------
# Monitoring
# ---------------------------------------------------------------------------------------------
def page_monitor():
    st.title("Monitoring")
    from src.tracing import Tracer

    df = Tracer(path("traces_db")).read()
    if df.empty:
        st.info("No traces yet. Every question asked in the app (and in evaluations) is logged to data/traces.db.")
        return
    src = st.radio("Source", ["all"] + sorted(df["source"].dropna().unique()), horizontal=True)
    if src != "all":
        df = df[df["source"] == src]
    k = st.columns(6)
    k[0].metric("Requests", len(df))
    k[1].metric("Answered", int((df["status"] == "ok").sum()))
    k[2].metric("Refused", int((df["status"] == "refused").sum()))
    k[3].metric("Latency p50", f"{df['t_total'].quantile(0.5):.1f} s")
    k[4].metric("Latency p95", f"{df['t_total'].quantile(0.95):.1f} s")
    k[5].metric("Avg attempts", f"{df['n_attempts'].mean():.2f}")
    df = df.copy()
    # Local time (ts is a Unix timestamp; without this the table showed UTC).
    df["time"] = df["ts"].map(lambda t: datetime.datetime.fromtimestamp(t).strftime("%Y-%m-%d %H:%M:%S"))
    st.dataframe(df[["id", "time", "source", "config", "model", "status", "n_attempts", "guard_blocks", "n_rows",
                     "t_total", "t_llm", "t_exec", "prompt_tokens", "completion_tokens", "question"]],
                 width="stretch", hide_index=True)
    pick = st.selectbox("Trace detail", list(df["id"]))
    if pick is not None:
        r = df[df["id"] == pick].iloc[0]
        st.markdown(f"**{r['question']}** - {r['status']}, {r['n_attempts']} attempt(s)")
        if pd.notna(r["final_sql"]) and r["final_sql"]:   # refusals have no SQL (NaN in the frame)
            st.code(r["final_sql"], language="sql")
        st.json(json.loads(r["attempts"] or "[]"), expanded=False)
        st.caption(f"Retrieved: {r['retrieved']}")


nav = st.navigation([
    st.Page(page_ask, title="Ask", default=True),          # served at the root URL
    st.Page(page_schema, title="Schema explorer", url_path="schema"),
    st.Page(page_eval, title="Evaluation", url_path="evaluation"),
    st.Page(page_monitor, title="Monitoring", url_path="monitoring"),
])
with st.sidebar:
    st.caption(ATTRIBUTION)
nav.run()
